# Generated by Django 4.1.8 on 2023-05-11 09:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('website', '0002_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteringTechnologyNightPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Metering Technology Night Page',
                'verbose_name_plural': 'Metering Technology Night Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PreConference',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('training_overview', wagtail.fields.RichTextField()),
                ('objective', wagtail.fields.RichTextField()),
                ('outcomes', wagtail.fields.RichTextField()),
                ('content', wagtail.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Pre-Conference Page',
                'verbose_name_plural': 'Pre-Conference Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SpeakerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('speaker_category', models.CharField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Speaker Page',
                'verbose_name_plural': 'Speaker Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TechnicalProgramPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Technical Program Page',
                'verbose_name_plural': 'Technical Program Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='speakers',
            name='speaker_category',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_type', to='website.speakerpage'),
        ),
    ]
