# Generated by Django 4.1.8 on 2023-05-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_socialmediasettings_importantpages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='email',
            field=models.EmailField(blank=True, help_text='Your Email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='Your Facebook page URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.CharField(blank=True, help_text='Your Instagram account URL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Your LinkedIn account URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter',
            field=models.URLField(blank=True, help_text='Your Twitter account URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='website',
            field=models.URLField(blank=True, help_text='Your Website URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='youtube',
            field=models.URLField(blank=True, help_text='Your YouTube channel or user account URL', null=True),
        ),
    ]
