# Generated by Django 4.1.8 on 2023-05-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_socialmediasettings_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preconference',
            old_name='content',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='preconference',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='preconference',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='preconference',
            name='training_overview',
        ),
    ]
