# Generated by Django 4.1.8 on 2023-08-13 21:49

from django.db import migrations
import wagtailcloudinary.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_content_preconference_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='company_logo',
            field=wagtailcloudinary.fields.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='photo',
            field=wagtailcloudinary.fields.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technicaladvisorycommittee',
            name='photo',
            field=wagtailcloudinary.fields.CloudinaryField(max_length=255, null=True),
        ),
    ]
