# Generated by Django 4.1.8 on 2023-08-14 12:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_attendees_company_logo_alter_speakers_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='company_logo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='technicaladvisorycommittee',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
