# Generated by Django 4.1.8 on 2023-11-14 13:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_attendees_company_logo_alter_speakers_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=500, null=True)),
                ('company_logo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('company_url', models.URLField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Sponsors',
                'verbose_name_plural': 'Sponsors',
            },
        ),
    ]
