# Generated by Django 4.1.8 on 2023-08-13 21:49

from django.db import migrations
import wagtailcloudinary.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_conferenceyearpage_galleryyearpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencegalleryimage',
            name='image',
            field=wagtailcloudinary.fields.CloudinaryField(max_length=255, null=True),
        ),
    ]
