# Generated by Django 4.1.8 on 2023-08-13 21:49

from django.db import migrations
import wagtailcloudinary.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_downloadreportform_report_download_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadreportform',
            name='report_cover_image',
            field=wagtailcloudinary.fields.CloudinaryField(max_length=255, null=True),
        ),
    ]
