# Generated by Django 4.1.8 on 2024-07-30 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_attendant_alter_user_company_alter_user_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Enter the currency type, e.g. Naira(NGN)', max_length=500, null=True)),
                ('symbol', models.CharField(blank=True, help_text='Enter the currency symbol, e.g. $', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Enter the category the registrant belongs to, e.g. Visitor', max_length=500, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendant',
            name='number_of_registrant',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attendant',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='attendant',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registration.currencytype'),
        ),
        migrations.AddField(
            model_name='attendant',
            name='registration_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registration.registrationtype'),
        ),
    ]
