# Generated by Django 4.1.8 on 2024-07-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_currencytype_registrationtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendant',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='attendant',
            name='number_of_registrant',
        ),
        migrations.RemoveField(
            model_name='attendant',
            name='registration_type',
        ),
        migrations.RemoveField(
            model_name='attendant',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='attendant',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last name'),
        ),
    ]
