# Generated by Django 5.0.7 on 2024-08-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_attendant_currency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyType',
        ),
        migrations.RemoveField(
            model_name='registrationpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='RegistrationType',
        ),
        migrations.RemoveField(
            model_name='visitorformfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='visitorregistrationformpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='visitorregistrationpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='RegistrationPage',
        ),
        migrations.DeleteModel(
            name='VisitorFormField',
        ),
        migrations.DeleteModel(
            name='VisitorRegistrationFormPage',
        ),
        migrations.DeleteModel(
            name='VisitorRegistrationPage',
        ),
    ]
