# Generated by Django 5.0.7 on 2024-08-08 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_delete_currencytype_remove_registrationpage_page_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
