# Generated by Django 5.0.7 on 2024-12-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_attendant_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendant',
            options={'ordering': ['-created_at']},
        ),
    ]
