# Generated by Django 4.1.8 on 2023-04-20 13:28

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('conference_name', models.CharField(max_length=500, null=True)),
                ('short_name', models.CharField(max_length=500, null=True)),
                ('year', models.IntegerField(null=True, unique=True)),
                ('theme', models.CharField(max_length=1000, null=True)),
                ('venue', models.CharField(blank=True, max_length=1000, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('short_description', wagtail.fields.RichTextField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254, null=True)),
                ('contact_phone_number', models.CharField(max_length=20, null=True)),
                ('about_cta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('register_cta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('sponsor_cta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Conference Page',
                'verbose_name_plural': 'Conference Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
