# Generated by Django 4.1.8 on 2023-06-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='dollar_payment_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
