# Generated by Django 4.1.8 on 2023-11-13 16:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_banner_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_image',
            new_name='slider1',
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider2',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider3',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider4',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
