# Generated by Django 4.1.8 on 2023-11-14 12:48

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_banner_image_homepage_slider1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='slider1_text',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider2_text',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider3_text',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider4_text',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
