# Generated by Django 4.1.8 on 2023-05-15 12:15

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshippage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
